project_id = "treehole-learn"

[api]
enabled = true
port = 46421
schemas = ["public", "storage"]

[db]
port = 46422
shadow_port = 46420
major_version = 15

[db.seed]
enabled = true
sql_paths = ["./seed.sql", "./seed_assessments.sql"]

[studio]
enabled = true
port = 46423

[auth]
enabled = true
site_url = "http://localhost:3006"
additional_redirect_urls = ["http://localhost:3006"]
jwt_expiry = 3600
enable_signup = false

[auth.email]
enable_signup = false
double_confirm_changes = true

[storage]
enabled = true
file_size_limit = "50MiB"
